# This workflow sets up and runs MSBuild and VSTest 
# to build and test a Visual Studio solution.

name: Build and Test

on:
  push:
    branches: [ "main", "test/*", "feature/*", "bugfix/*"]
  pull_request:
    branches: ["main", "test/*", "feature/*", "bugfix/*"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Run MSBuild
      id: run_msbuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild .\build\cbcr.sln

# - name: Setup VSTest and add to PATH
#      uses: darenm/Setup-VSTest@v1
#      id: setup_vstest
      
#    - name: Run VSTest
#      id: run_vstest
#      working-directory: ${{env.GITHUB_WORKSPACE}}
#      run: vstest.console.exe /Platform:x64 .\Regresie_Lineara\x64\Debug\Native_tests.dll
